return _G.SharpMod.cheat_manager:add('infinite_equipment', 'Infinite equipment', function()
    PlayerManager.set_infinite_equipment(0, true)
end, function()
    PlayerManager.set_infinite_equipment(0, false)
end)
