name: Main

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nebularg/actions-luacheck@v1
        with:
          args: '--no-color --codes -q'
          annotate: warning
